version: '3.8'
services:
  vue-app:
    build: .
    image: vue-app:1.0
    container_name: vue-app
    tty: true                    # docker run -t => pseudo-terminal inside real terminal
    stdin_open: true             # docker run -i => standard i/o
#   env_file:
#     - .env
#   environment:
#     - VUE_APP_TEST_EVN=testEnv

    networks:
       vue-nest-network:
         ipv4_address: 172.25.0.5
    ports:
      - 8080:8080
    volumes:
      - .:/home/vue-app

networks:
  vue-nest-network:
#   external: true                # pre-existing network  # when docker-compose down => network not removed
    name: vue-nest-network
    driver: bridge
#   enable_ipv6: false
    ipam:
#     driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1